### PR TITLE
Add list of groot services to README

### PR DESCRIPTION
**Pull request by bcongdon**
Addresses https://github.com/acm-uiuc/groot/issues/38

### CODE REVIEW

**Comment by aashishkapur** [comment]
Do we want to have descriptions for all of the services? 

Also, do we want to put down languages for each of the services?

**Comment by sameetandpotatoes** [comment]
I think descriptions is okay - they could update (not that often/likely), but this would become another source to change.

If this is for newcomers, as @aashishkapur says it may be a good idea to separate the list of repos by languages so that new devs can align with different repos.

**Comment by narendasan** [comment]
Would say that we should have separation by language in this PR, would be good for open house. Descriptions are sufficient for now, I see this being ported to a docs site (perhaps integrated with canopy so we have a single dev and management portal for groot)

**Comment by bcongdon** [comment]
I broke out the projects by language, lmk if anyone has any other suggestions

**Comment by aashishkapur** [comment]
User service is in Ruby, not JS

Quotes - Manages quotes heard around the ACM office
Recruiter-templates - Holds template used by the Recruiter service to send emails

**Pull request merged**
