### PR TITLE
Docker for auth-stub-service

### PR DESCRIPTION
**Pull request by bcongdon**
Addresses https://github.com/acm-uiuc/groot-auth-stub-service/issues/1

### CODE REVIEW

**Comment by narendasan** [comment]
Will this spin up the stub service in prod? Seems like it will bring it up but the config in the api gateway will point requests to crowd. Are we ok with this or is there some sort of boot variable we can pass in the cli to bring up the stub service only for dev?

**Comment by bcongdon** [comment]
It seems like the `docker-compose` 'sanctioned' method for doing that would be to have a separate compose file for prod/dev https://docs.docker.com/compose/production/

**Comment by narendasan** [comment]
idk what would be better overall, reducing complexity is nice but not having code running that has nothing to do with prod operation is good too

**Comment by sameetandpotatoes** [comment]
A separate compose file for dev and prod seems like the way to go.

**Comment by bcongdon** [comment]
kk. I split out a prod version of the docker-compose file and cleaned up some of the unused docker files.

**Comment by narendasan** [comment]
@bcongdon can you also move and modify the spinup scripts so they run out of the scripts folder. would be good to have the root directory as clean as possible

**Comment by bcongdon** [comment]
Yup, done. 👍 Meant to do that at some point...

**Pull request merged**
